import { readFileSync, writeFileSync } from 'node:fs';
import { mentors } from '../../src/data/mentors.ts';

export function generatedValidation() {
  const source = readFileSync(new URL('../../shared/xperts-validation.mjs', import.meta.url), 'utf8');
  return '// Generated by node integrations/xperts/build-script.mjs. Do not edit.\n' +
    'const XPERTS_MENTOR_NAMES = ' + JSON.stringify(Object.fromEntries(mentors.map(m => [m.id, m.name])), null, 2) + ';\n' +
    source.replace('export default function', 'function');
}
writeFileSync(new URL('../xcelerate/XpertsValidation.gs', import.meta.url), generatedValidation());
